"""
Schemas for the Skill Bridge application.
"""

from typing import List, Optional

from pydantic import BaseModel, Field


class Entity(BaseModel):
    """Schema for a named entity."""

    text: str = Field(..., description="The entity text")
    label: str = Field(..., description="The entity label")


class MatchDetail(BaseModel):
    """Schema for skill match details."""

    job_skill: str = Field(..., description="Skill required by the job")
    best_match: Optional[str] = Field(
        None, description="Best matching skill from resume"
    )
    similarity: float = Field(..., description="Similarity score for the match")
    is_match: bool = Field(
        ..., description="Whether the similarity exceeds the threshold"
    )


# Course recommendation schemas


class CourseRecommendation(BaseModel):
    """Schema for a course recommendation."""

    course_name: str = Field(..., description="The name of the recommended course")
    url: str = Field(..., description="URL to access the course")
    description: str = Field("", description="Brief description of the course")
    potential_score: float = Field(
        0.0, description="Potential job match score if this course is completed"
    )
    score_improvement: float = Field(
        0.0, description="Score improvement over current skills"
    )


class CourseRecommendationRequest(BaseModel):
    """Request schema for generating course recommendations based on skill gap."""

    resume_text: str = Field(..., description="The resume text to analyze")
    job_description_text: str = Field(
        ..., description="The job description text to analyze"
    )
    threshold: float = Field(
        0.5, description="Similarity threshold for considering skills as a match"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "resume_text": "PROFESSIONAL SUMMARY\nExperienced software engineer with 7 years of experience developing web applications using React, TypeScript, and Node.js. Strong background in cloud architecture with AWS. Proven ability to design scalable solutions and mentor junior developers.\n\nSKILLS\nProgramming Languages: JavaScript, TypeScript, Python\nFrontend: React, Redux, HTML5, CSS3, SASS\nBackend: Node.js, Express, NestJS\nDatabases: MongoDB, PostgreSQL, MySQL\nCloud: AWS (EC2, S3, Lambda), Docker, Kubernetes\nTools: Git, JIRA, CI/CD pipelines\n\nEXPERIENCE\nSenior Software Engineer at TechCorp\nLed development of a customer-facing portal using React and TypeScript\nImplemented serverless architecture using AWS Lambda and API Gateway\nReduced page load time by 40% through code optimization\n",
                "job_description_text": "We are looking for a Software Engineer with 5+ years of experience in React, Node.js, and TypeScript. The ideal candidate should have strong problem-solving skills and experience with AWS, Docker, and CI/CD pipelines. Knowledge of Python and machine learning frameworks like TensorFlow or PyTorch is a plus. Must be located in San Francisco or willing to relocate.",
                "threshold": 0.5,
            }
        }
    }


class CourseRecommendationResponse(BaseModel):
    """Response schema for course recommendation results."""

    recommended_courses: List[CourseRecommendation] = Field(
        default_factory=list,
        description="List of recommended courses to address skill gaps",
    )
    skill_gap: List[str] = Field(
        default_factory=list,
        description="Skills from job description that are missing in the resume",
    )
    job_skills: List[str] = Field(
        default_factory=list,
        description="Skills identified in the job description",
    )
    user_skills: List[str] = Field(
        default_factory=list,
        description="Skills identified in the user resume",
    )
    recommendations_text: Optional[str] = Field(
        None, description="Full text of the recommendations generated by the LLM"
    )
    matching_details: List[MatchDetail] = Field(
        default_factory=list,
        description="Detailed matching information for each job skill",
    )
