"""
Schemas for the Skill Bridge application.
"""

from typing import List, Optional

from pydantic import BaseModel, Field


class Entity(BaseModel):
    """Schema for a named entity."""

    text: str = Field(..., description="The entity text")
    label: str = Field(..., description="The entity label")


class MatchDetail(BaseModel):
    """Schema for skill match details."""

    job_skill: str = Field(..., description="Skill required by the job")
    best_match: Optional[str] = Field(
        None, description="Best matching skill from resume"
    )
    similarity: float = Field(..., description="Similarity score for the match")
    is_match: bool = Field(
        ..., description="Whether the similarity exceeds the threshold"
    )


# Course recommendation schemas


class CourseRecommendation(BaseModel):
    """Schema for a course recommendation."""

    course_name: str = Field(..., description="The name of the recommended course")
    url: str = Field(..., description="URL to access the course")
    description: str = Field("", description="Brief description of the course")


class CourseRecommendationRequest(BaseModel):
    """Request schema for generating course recommendations based on skill gap."""

    resume_text: str = Field(..., description="The resume text to analyze")
    job_description_text: str = Field(
        ..., description="The job description text to analyze"
    )
    threshold: float = Field(
        0.5, description="Similarity threshold for considering skills as a match"
    )


class CourseRecommendationResponse(BaseModel):
    """Response schema for course recommendation results."""

    recommended_courses: List[CourseRecommendation] = Field(
        default_factory=list,
        description="List of recommended courses to address skill gaps",
    )
    skill_gap: List[str] = Field(
        default_factory=list,
        description="Skills from job description that are missing in the resume",
    )
    job_skills: List[str] = Field(
        default_factory=list,
        description="Skills identified in the job description",
    )
    user_skills: List[str] = Field(
        default_factory=list,
        description="Skills identified in the user resume",
    )
    recommendations_text: Optional[str] = Field(
        None, description="Full text of the recommendations generated by the LLM"
    )
    matching_details: List[MatchDetail] = Field(
        default_factory=list,
        description="Detailed matching information for each job skill",
    )
